experiment:
  seed: 88
  save_dir: ../experiments/classify/


data: 
  annotations: ../data/rsna18/train_kfold_for_covid.csv
  data_dir: ../data/rsna18/stage_2_train_images/
  input: filename
  target: label
  outer_fold: 0
  dataset:
    name: DICOMDataset
    params:
      flip: true
      verbose: true
      repeat_rgb: true


transform:
  resize:
    name: resize
    params:
      imsize: [352, 352]
  augment:
    name: grayscale_augment
    params:
      n: 3
      p: 0.9
  crop:
    null
  preprocess: 
    name: Preprocessor
    params:
      image_range: [0, 255]
      input_range: [0, 1]
      mean: [0.5, 0.5, 0.5]
      sdev: [0.5, 0.5, 0.5]


task: 
  name: ClassificationTask
  params: 


model:
  name: Net2D
  params:
    backbone: tf_efficientnet_b4
    pretrained: true
    num_classes: 3
    dropout: 0.2
    in_channels: 3
    multisample_dropout: true
    pool: avg


loss:
  name: CrossEntropyLoss
  params:


optimizer:
  name: AdamW
  params:
    lr: 3.0e-4
    weight_decay: 5.0e-4


scheduler: 
  name: CosineAnnealingLR
  params:
    final_lr: 0.0


train:
  batch_size: 16
  num_epochs: 10


evaluate: 
  metrics: [AUROC, Accuracy]
  monitor: auc_mean
  mode: max


