experiment:
  seed: 88
  save_dir: ../experiments/classify/


data: 
  annotations: ../data/covid/train_kfold_cleaned_w_bboxes_yuji.csv
  data_dir: ../data/covid/train_pngs/
  input: filename
  target: [negative, atypical, indeterminate, typical, none]
  outer_fold: 0
  dataset:
    name: ImageDataset
    params:
      flip: false
      verbose: true


transform:
  resize:
    name: resize_ignore
    params:
      imsize: [384, 384]
  augment:
    name: simple_augment
    params:
      p: 1.0
  crop:
    null
  preprocess: 
    name: Preprocessor
    params:
      image_range: [0, 255]
      input_range: [0, 1]
      mean: [0.5, 0.5, 0.5]
      sdev: [0.5, 0.5, 0.5]


task: 
  name: ClassificationTask
  params: 


model:
  name: Net2D
  params:
    backbone: swin_large_patch4_window12_384_in22k
    pretrained: true
    num_classes: 5
    dropout: 0.2
    in_channels: 3
    multisample_dropout: true
    pool: avg
    load_pretrained: ../experiments/classify/mk030/sbn/checkpoints/epoch007-vm0.8754.ckpt


loss:
  name: BCEWithLogitsLoss
  params:


optimizer:
  name: Adam
  params:
    lr: 1.0e-4


scheduler: 
  name: CosineAnnealingLR
  params:
    final_lr: 1.0e-6


train:
  batch_size: 8
  num_epochs: 10


evaluate: 
  metrics: [AUROC, AVP]
  monitor: auc_mean
  mode: max


