experiment:
  seed: 88
  save_dir: ../experiments/classify/


data: 
  annotations: ../data/rsna18/train_kfold_for_covid_w_bboxes.csv
  data_dir: ../data/rsna18/stage_2_train_images/
  input: filename
  target: [negative, not_normal, opacity]
  outer_fold: 0
  dataset:
    name: SegmentClassify
    params:
      flip: true
      verbose: true
      dicom: true


transform:
  resize:
    name: resize_ignore
    params:
      imsize: [512, 512]
  augment:
    name: grayscale_augment
    params:
      n: 3
      p: 0.9
  crop:
    null
  preprocess: 
    name: Preprocessor
    params:
      image_range: [0, 255]
      input_range: [0, 1]
      mean: [0.5, 0.5, 0.5]
      sdev: [0.5, 0.5, 0.5]


task: 
  name: HybridTask
  params: 


model:
  name: NetSMPHybrid
  params:
    segmentation_model: DeepLabV3Plus
    encoder_name: timm-efficientnet-b4
    classes: 1
    segment_dropout: 0.2
    aux_params:
      dropout: 0.2
      classes: 3
    load_pretrained: null


loss:
  name: HybridClsSegLoss
  params:
    seg_weight: 1.0
    use_weighted_bce: False


optimizer:
  name: AdamW
  params:
    lr: 3.0e-4
    weight_decay: 5.0e-4


scheduler: 
  name: CosineAnnealingLR
  params:
    final_lr: 1.0e-6


train:
  batch_size: 4
  num_epochs: 8


evaluate: 
  metrics: [AUROC, AVP]
  monitor: avp_mean
  mode: max


