experiment:
  seed: 89
  save_dir: ../experiments/classify/


data: 
  annotations: ../data/covid/train_kfold_cleaned_w_bboxes_yuji.csv
  data_dir: ../data/covid/train_pngs/
  input: filename
  target: [negative, atypical, indeterminate, typical, none]
  outer_fold: 0
  dataset:
    name: SegmentClassify
    params:
      flip: true
      verbose: true


transform:
  resize:
    name: resize_ignore
    params:
      imsize: [384, 384]
  augment:
    name: simple_augment
    params:
      p: 1.0
  crop:
    null
  preprocess: 
    name: Preprocessor
    params:
      image_range: [0, 255]
      input_range: [0, 1]
      mean: [0.5, 0.5, 0.5]
      sdev: [0.5, 0.5, 0.5]


task: 
  name: HybridTask
  params: 
    mixaug:
      mixup: 0.4


model:
  name: SwinDeepLabV3Plus
  params:
    load_pretrained_encoder: ../experiments/classify/mk030/sbn/checkpoints/last.ckpt
    segment_dropout: 0.2
    classes: 1
    aux_params:
      dropout: 0.2
      classes: 5


loss:
  name: MixHybridClsSegLoss
  params:
    seg_weight: 1.0
    use_weighted_bce: False



optimizer:
  name: Adam
  params:
    lr: 1.0e-4


scheduler: 
  name: CosineAnnealingLR
  params:
    final_lr: 1.0e-6


train:
  batch_size: 8
  num_epochs: 10


evaluate: 
  metrics: [AUROC, AVP]
  monitor: auc_mean
  mode: max


