experiment:
  seed: 88
  save_dir: ../experiments/detect/


data: 
  annotations: ../data/rsna18/train_bbox_annotations_effdet.pkl
  data_dir: ../data/rsna18/stage_2_train_images/
  outer_fold: 0
  dataset:
    name: DICOMDataset
    params:
      flip: true
      verbose: true
  exclude_negative_train: true
  exclude_negative_valid: true


transform:
  resize:
    name: resize_ignore
    params:
      imsize: [256, 256]
  augment:
    name: grayscale_augment
    params:
      p: 0.9
      n: 3
  preprocess:
    name: Preprocessor
    params:
      image_range: [0, 255]
      input_range: [0, 1]
      mean: [0.5, 0.5, 0.5]
      sdev: [0.5, 0.5, 0.5]


task: 
  name: DetectionTask
  params: 


model:
  name: EffDet
  params:
    base: tf_efficientdet_d0
    backbone: tf_efficientnet_b0
    num_classes: 1
    pretrained: true
    image_size: [256, 256]


loss:
  name: DetectionLoss
  params:



optimizer:
  name: AdamW
  params:
    lr: 5.0e-6
    weight_decay: 5.0e-4


scheduler: 
  name: CustomOneCycleLR
  params:
    max_lr: 5.0e-4
    final_lr: 0.0
    pct_start: 0.1


train:
  batch_size: 8
  num_epochs: 12


evaluate: 
  metrics: 
    - name: mAP
      params: 
        num_classes: 1
  monitor: map
  mode: max


